version: 0.2

env:
  variables:
    CLUSTER_NAME: "pdf-cluster"
    AWS_REGION: "us-east-1"
    NAMESPACE: "default"
    DEPLOYMENT_FILE: "k8s-deployment.yaml"

phases:
  pre_build:
    commands:
      - echo "Setting up kubeconfig"
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION --role-arn arn:aws:iam::969317006731:role/codebuild-eks-deploy-role
      - kubectl version --short

  build:
    commands:
      - echo "Applying Kubernetes manifests"
      - kubectl apply -f $DEPLOYMENT_FILE --validate=false
      - echo "Rollout status"
      - kubectl rollout status deployment/pdf-backend -n $NAMESPACE

artifacts:
  files:
    - "**/*"
