version: 0.2

env:
  variables:
    CLUSTER_NAME: "app-cluster"
    AWS_REGION: "us-east-1"

phases:
  install:
    commands:
      - curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo "Configuring kubeconfig"
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION
      - kubectl get nodes

  build:
    commands:
      - echo "Deploying manifests"
      - kubectl apply -f k8s/ --recursive
      - echo "Waiting for deployment rollout"
      - kubectl rollout status deployment/pdf-backend

  post_build:
    commands:
      - kubectl get svc -A
      - kubectl get pods -A
